services:
  luminus:
    image: clojure:latest
    # user: vscode
    ports:
      - "3020:3020"
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    working_dir: /usr/src/app
    entrypoint:
      - sleep
      - infinity

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: wil
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  gitlibs:
    external: true
  m2:
    external: true
  data:
    driver: local
